name: Build Release from Shared Workflow

on:
  release:
    types: ["created"]

jobs:
  call-builder-workflow:
    permissions:
      contents: read
      packages: write
    uses: Dartmouth-OpenAV/shared-workflows/.github/workflows/build_release.yaml@main