name: Build Latest from Shared Workflow

on:
  push:
    branches: ["main"]

jobs:
  call-builder-workflow:
    permissions:
      contents: read
      packages: write
    uses: Dartmouth-OpenAV/shared-workflows/.github/workflows/build_latest.yaml@main